# Generated by Django 3.1.7 on 2021-04-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billbook', '0002_auto_20210425_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billbook',
            name='pick_up_date',
            field=models.TextField(),
        ),
    ]
