# Generated by Django 3.1.7 on 2021-04-24 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField()),
                ('status', models.TextField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicing.location')),
                ('user', models.ManyToManyField(to='user.User')),
                ('vehicle', models.ManyToManyField(to='vehicle.Vehicle')),
            ],
        ),
    ]
