# Generated by Django 3.1.7 on 2021-04-25 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_vehicles'),
        ('vehicle', '0002_vehicle_user'),
        ('servicing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicing',
            name='location',
        ),
        migrations.AddField(
            model_name='servicing',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='servicing',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.RemoveField(
            model_name='servicing',
            name='user',
        ),
        migrations.AddField(
            model_name='servicing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
        ),
        migrations.RemoveField(
            model_name='servicing',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='servicing',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle.vehicle'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
