# Generated by Django 3.1.7 on 2021-04-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0002_auto_20210425_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicing',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='servicing',
            name='color',
            field=models.TextField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicing',
            name='license_plate_no',
            field=models.TextField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='servicing',
            name='vehicle_name',
            field=models.TextField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='servicing',
            name='vehicle_type',
            field=models.TextField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicing',
            name='latitude',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='servicing',
            name='longitude',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
