# Generated by Django 3.1.7 on 2021-05-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
