# Generated by Django 3.1.7 on 2021-04-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(max_length=500)),
                ('fullname', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('vehicles', models.ManyToManyField(to='vehicle.Vehicle')),
            ],
        ),
    ]
