# Generated by Django 3.1.7 on 2021-04-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vehicles',
            new_name='vehicle',
        ),
    ]
