# Generated by Django 3.1.7 on 2021-04-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210424_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vehicle',
            new_name='vehicles',
        ),
    ]
