# Generated by Django 3.1.7 on 2021-04-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210424_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vehicles',
        ),
    ]
